services:
  - type: worker
    name: classplus-video-bot-pyrogram
    runtime: docker
    repo: https://github.com/yourusername/classplus-video-bot.git
    branch: main
    dockerfilePath: ./Dockerfile

    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false  # Telegram API ID
      - key: API_HASH
        sync: false  # Telegram API Hash
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
      - key: TZ
        value: "UTC"
      - key: FFMPEG_LOGLEVEL
        value: "error"
      - key: MAX_FILE_SIZE_MB
        value: "2048"  # 2GB support with Pyrogram
      - key: INPUT_FILE_SIZE_MB
        value: "2048"
      - key: MAX_CONCURRENT_DOWNLOADS
        value: "1"
      - key: DOWNLOAD_TIMEOUT
        value: "1800"  # 30 minutes
      - key: UPLOAD_TIMEOUT
        value: "3600"  # 1 hour for 2GB uploads
      - key: PROGRESS_UPDATE_INTERVAL
        value: "10"    # Progress updates every 10%

    scaling:
      minInstances: 1
      maxInstances: 1

    disk:
      name: classplus-bot-storage
      mountPath: /tmp/videos
      sizeGB: 100  # Increased for 2GB file handling

    plan: standard
